import Appbar from "./sections/Header/Appbar";
import Topbar from "./sections/Header/Topbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-background-light dark:bg-background-dark text-dark dark:text-light font-sans `}
      >
        <Topbar />
        <Appbar />
        {children}

        <div id="service-portal" />
      </body>
    </html>
  );
}
